[package]
name = "truck-topology"
version = "0.6.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "topological structs: vertex, edge, wire, face, shell, and solid"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[dependencies]
serde = { workspace = true }
rayon = { workspace = true }
rustc-hash = { workspace = true }
truck-base = { workspace = true }
truck-geotrait = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
rclite = { version = "0.3.0", optional = true }

[features]
default = ["rclite"]
nightly = ["parking_lot/nightly"]

[dev-dependencies]
