[package]
name = "truck-topology"
version = "0.5.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "topological structs: vertex, edge, wire, face, shell, and solid"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[dependencies]
serde = { version = "1.0.174", features = ["derive"] }
rayon = "1.7.0"
rustc-hash = "1.1.0"
truck-base = { version = "0.4.0", path = "../truck-base" }
truck-geotrait = { version = "0.3.0", path = "../truck-geotrait" }
thiserror = "1.0.44"
parking_lot = "0.12.1"
rclite = { version = "0.2.4", optional = true }

[features]
default = ["rclite"]
nightly = ["parking_lot/nightly"]

[dev-dependencies]
