[package]
name = "truck-shapeops"
version = "0.4.0"
edition = "2021"
description = "Provides boolean operations to Solid"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

[features]
default = ["step-test"]
step-test = ["truck-stepio"]

[dependencies]
derive_more = { workspace = true }
rustc-hash = { workspace = true }
itertools = { workspace = true }
truck-base = { workspace = true }
truck-geometry = { workspace = true }
truck-topology = { workspace = true }
truck-meshalgo = { workspace = true }

truck-geotrait = { workspace = true }
truck-stepio = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }
serde_json = { workspace = true }
truck-modeling = { workspace = true }
proptest = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { workspace = true }
