[package]
name = "truck-rendimpl"
version = "0.6.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "visualization of shape and polygon mesh based on platform"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["*.png"]

[features]
default = []
webgl = ["truck-platform/webgl"]

[dependencies]
itertools = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
truck-platform = { workspace = true }
truck-polymesh = { workspace = true }

[dev-dependencies]
async-trait = "0.1.89"
env_logger = { workspace = true }
pollster = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
truck-meshalgo = { workspace = true }
truck-modeling = { workspace = true }
winit = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
web-time = { workspace = true }
wasm-bindgen-futures = { workspace = true }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
web-sys = { workspace = true, features = ["Location"] }
