[package]
name = "truck-rendimpl"
version = "0.5.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "visualization of shape and polygon mesh based on platform"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["*.png"]

[features]
default = []
webgl = ["truck-platform/webgl"]

[dependencies]
itertools = "0.12.1"
bytemuck = { version = "1.16.1", features = ["derive"] }
image = "0.25.1"
truck-platform = { version = "0.5.0", path = "../truck-platform" }
truck-polymesh = { version = "0.5.0", path = "../truck-polymesh" }

[dev-dependencies]
async-trait = "0.1.80"
env_logger = "0.11.3"
pollster = "0.3.0"
rayon = "1.10.0"
serde_json = "1.0.117"
truck-meshalgo = { version = "0.3.0", path = "../truck-meshalgo" }
truck-modeling = { version = "0.5.0", path = "../truck-modeling" }
winit = "0.29.15"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
web-time = "=0.2.4"
wasm-bindgen-futures = "0.4.42"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
web-sys = { version = "=0.3.67", features = ["Location"] }
