[package]
name = "truck-rendimpl"
version = "0.6.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "visualization of shape and polygon mesh based on platform"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["*.png"]

[features]
default = []
webgl = ["truck-platform/webgl"]

[dependencies]
itertools = "0.13.0"
bytemuck = { version = "1.21.0", features = ["derive"] }
image = "0.25.5"
truck-platform = { version = "0.6.0", path = "../truck-platform" }
truck-polymesh = { version = "0.6.0", path = "../truck-polymesh" }

[dev-dependencies]
async-trait = "0.1.83"
env_logger = "0.11.6"
pollster = "0.3.0"
rayon = "1.10.0"
serde_json = "1.0.134"
truck-meshalgo = { version = "0.4.0", path = "../truck-meshalgo" }
truck-modeling = { version = "0.6.0", path = "../truck-modeling" }
winit = "0.30.7"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
web-time = "1.1.0"
wasm-bindgen-futures = "0.4.49"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
web-sys = { version = "0.3.76", features = ["Location"] }
