[package]
name = "truck-platform"
version = "0.5.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "graphic utility library based on wgpu"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[features]
default = []
webgl = ["wgpu/webgl"]

[dependencies]
bytemuck = { version = "1.16.3", features = ["derive"] }
derive_more = "0.99.18"
futures-intrusive = "0.5.0"
rustc-hash = "2.0.0"
truck-base = { version = "0.4.0", path = "../truck-base" }
wgpu = "22.1.0"
winit = "0.30.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "1.1.0"
web-sys = "0.3.69"

[dev-dependencies]
image = "0.25.2"
rayon = "1.10.0"
env_logger = "0.11.5"
naga = { version = "22.1.0", features = ["wgsl-in"] }
pollster = "0.3.0"
log = "0.4.22"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4.42"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
web-sys = { version = "0.3.69", features = ["Location"] }
