[package]
name = "truck-platform"
version = "0.5.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "graphic utility library based on wgpu"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[features]
default = []
webgl = ["wgpu/webgl"]
wgpu_trace = ["wgpu/trace"]

[dependencies]
bytemuck = { version = "1.15.0", features = ["derive"] }
derive_more = "0.99.17"
futures-intrusive = "0.5.0"
rustc-hash = "1.1.0"
truck-base = { version = "0.4.0", path = "../truck-base" }
wgpu = "0.19.3"
winit = "0.29.15"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "=0.2.4"
web-sys = "=0.3.67"

[dev-dependencies]
image = "0.25.1"
rayon = "1.10.0"
env_logger = "0.11.3"
naga = { version = "0.19.2", features = ["wgsl-in"] }
pollster = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4.42"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
web-sys = { version = "=0.3.67", features = ["Location"] }
