[package]
name = "truck-assembly"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"
truck-base = { version = "0.5.0", path = "../truck-base" }

[dev-dependencies]
proptest = { version = "1.9.0", features = ["attr-macro"] }
