[package]
name = "truck-assembly"
version = "0.1.0"
edition = "2024"

[dependencies]
typed-arena = "2.0.2"
rustc-hash = "2.1.1"
itertools = "0.14.0"

truck-base = { version = "0.5.0", path = "../truck-base" }
