[package]
name = "truck-assembly"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = { workspace = true }
truck-base = { workspace = true }

[dev-dependencies]
proptest = { workspace = true, features = ["attr-macro"] }
