[package]
name = "truck-geometry"
version = "0.4.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "geometrical structs: knot vector, B-spline and NURBS"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
truck-base = { version = "0.4.0", path = "../truck-base" }
truck-geotrait = { version = "0.3.0", path = "../truck-geotrait" }

[dev-dependencies]
rand = "0.8.5"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.2.8", features = ["js"] }
