[package]
name = "truck-stepio"
version = "0.2.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "Reads/writes STEP files from/to truck"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[features]
default = ["in", "derive"]
in = ["derive_more", "ruststep", "serde", "truck-geotrait"]
derive = ["truck-derivers"]

[dependencies]
chrono = { version = "0.4.38", features = ["wasmbind"] }
derive_more = { version = "0.99.18", optional = true }
ruststep = { git = "https://github.com/ricosjp/ruststep.git", optional = true }
serde = { version = "1.0.204", features = ["derive"], optional = true }
truck-geometry = { version = "0.4.0", path = "../truck-geometry" }
truck-geotrait = { version = "0.3.0", path = "../truck-geotrait", optional = true }
truck-derivers = { version = "0.1.0", path = "../truck-derivers", optional = true }
truck-modeling = { version = "0.5.0", path = "../truck-modeling" }
truck-polymesh = { version = "0.5.0", path = "../truck-polymesh" }
truck-topology = { version = "0.5.0", path = "../truck-topology" }

[dev-dependencies]
clap = { version = "4.5.12", features = ["derive"] }
espr-derive = "0.3.0"
itertools = "0.12.1"
serde_json = "1.0.121"
truck-meshalgo = { version = "0.3.0", path = "../truck-meshalgo" }
truck-shapeops = { version = "0.3.0", path = "../truck-shapeops" }
proptest = "1.5.0"
