[package]
name = "truck-stepio"
version = "0.3.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "Reads/writes STEP files from/to truck"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[features]
default = ["in", "derive"]
in = ["derive_more", "ruststep", "serde", "truck-geotrait"]
derive = ["truck-derivers"]

[dependencies]
chrono = { version = "0.4.43", features = ["wasmbind"] }
derive_more = { workspace = true, optional = true }
ruststep = { version = "0.4.0", optional = true }
serde = { workspace = true, optional = true }
truck-assembly = { workspace = true }
truck-geometry = { workspace = true }
truck-geotrait = { workspace = true, optional = true }
truck-derivers = { workspace = true, optional = true }
truck-modeling = { workspace = true }
truck-polymesh = { workspace = true }
truck-topology = { workspace = true }

[dev-dependencies]
clap = { version = "4.5.57", features = ["derive"] }
espr-derive = "0.4.0"
itertools = { workspace = true }
serde_json = { workspace = true }
truck-meshalgo = { workspace = true }
truck-shapeops = { workspace = true }
proptest = { workspace = true }
